### ISSUE TITLE
Repository release checklist

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/cookiecutter-nautobot-app#10]
- [ ] Add README
- [ ] Review and update PR/Issue templates
- [ ] Update CODEOWNERS
- [ ] Add CI and review `test_bake_nautobot_plugin.py`
- [ ] Review contents of nautobot-app/README.md
- [ ] Review plugin template code - models.py has lots of comments and (outdated?) docs links
- [ ] Should `tasks.py` and `invoke.*.yml` be common across templates?
