### ISSUE TITLE
Public Release Checklist

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/cookiecutter-nautobot-app#44]
- [x] Finalize 1.6 version of cookie (possibly tag needs to be updated?)
- [x] Finalize 2.0 version of cookie
- [x] Write blog post @whitej6 
- [x] Update README and add docs website
    - [x] Set up docs scaffolding @cmsirbu #45 
    - [x] Fill in any extra docs @whitej6
